In [64]:
import pandas
import math
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

FNAME = '../cps09mar.dta'
df0 = pandas.read_stata(FNAME)

df = df0[ (df0.race == 2) ]

In [65]:
list(df)

['age',
 'female',
 'hisp',
 'educ',
 'earnings',
 'hours',
 'week',
 'union',
 'uncov',
 'region',
 'race',
 'marital',
 'black',
 'lwage',
 'exp',
 'white',
 'wage',
 'exp2']

In [68]:
#part b - model set up
#dropped variables Hispanic, black, Americian Indian, Asian, Mixed Race from the table in 4.1
y = pandas.DataFrame()
y = df['lwage']
X = df.loc[:,('educ','exp','female')]
X['exp_sq'] = X['exp']**2/100
X['union'] = df['union']
X['female*union'] = df['female'].multiply(df['union'])
#X['male*union'] = (1-df['female']).multiply(df['union'])

maritalstatus = pandas.get_dummies(df['marital']).loc[:,(1,2,3,4,5,6)]
maritalstatus['married'] = maritalstatus[1] +maritalstatus[2] + maritalstatus[3]
maritalstatus['former'] = maritalstatus[4] + maritalstatus[5] +maritalstatus[6]
X['married'] = maritalstatus['married']
X['married*female'] = df['female'].multiply(maritalstatus['married'])
X['former'] = maritalstatus['former']
X['former*female'] = df['female'].multiply(maritalstatus['former'])


sm.add_constant(X)

,const,educ,exp,female,exp_sq,union,female*union,married,married*female,former,former*female
111,1.0,13,36.0,0,12.960000,0,0,0,0,1,0
313,1.0,14,35.0,0,12.250000,0,0,1,0,0,0
519,1.0,13,21.0,0,4.410000,0,0,0,0,1,0
521,1.0,12,43.0,0,18.490000,0,0,0,0,1,0
645,1.0,13,26.0,1,6.760000,0,0,0,0,1,1
687,1.0,13,33.0,0,10.890000,0,0,1,0,0,0
1079,1.0,12,28.0,0,7.840000,0,0,0,0,1,0
1144,1.0,20,25.0,0,6.250000,0,0,1,0,0,0
1190,1.0,13,28.0,1,7.840000,0,0,0,0,1,1
1228,1.0,16,14.0,0,1.960000,0,0,0,0,0,0
1281,1.0,12,19.0,0,3.610000,0,0,1,0,0,0
1319,1.0,16,15.0,0,2.250000,0,0,1,0,0,0
1410,1.0,12,25.0,0,6.250000,0,0,1,0,0,0
1419,1.0,14,28.0,0,7.840000,0,0,1,0,0,0
1548,1.0,16,28.0,0,7.840000,0,0,1,0,0,0
1642,1.0,13,24.0,0,5.760000,0,0,0,0,1,0
1961,1.0,16,6.0,1,0.360000,0,0,0,0,0,0
2249,1.0,18,31.0,0,9.610000,0,0,1,0,0,0
2371,1.0,14,37.0,0,13.690000,0,0,1,0,0,0
2417,1.0,18,18.0,0,3.240000,0,0,1,0,0,0
2418,1.0,18,12.0,1,1.440000,0,0,1,1,0,0
2776,1.0,20,21.0,1,4.410000,0,0,1,1,0,0
2777,1.0,13,20.0,1,4.000000,0,0,0,0,0,0
2815,1.0,14,28.0,1,7.840000,0,0,1,1,0,0
2816,1.0,0,39.0,0,15.210000,0,0,0,0,0,0
2818,1.0,13,10.0,0,1.000000,0,0,0,0,0,0
2819,1.0,16,8.0,1,0.640000,0,0,0,0,0,0
2826,1.0,12,23.0,0,5.290000,0,0,0,0,1,0
2827,1.0,14,32.0,1,10.240000,0,0,0,0,1,1
2828,1.0,16,17.0,0,2.890000,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
49489,1.0,12,29.0,1,8.410000,0,0,1,1,0,0
49504,1.0,14,20.0,1,4.000000,0,0,0,0,1,1
49524,1.0,12,2.0,0,0.040000,0,0,1,0,0,0
49563,1.0,13,20.0,0,4.000000,0,0,0,0,0,0
49614,1.0,14,21.0,0,4.410000,0,0,1,0,0,0
49615,1.0,14,21.0,1,4.410000,0,0,1,1,0,0
49637,1.0,12,8.0,0,0.640000,0,0,1,0,0,0
49662,1.0,12,36.0,1,12.960000,0,0,0,0,1,1
49663,1.0,18,11.0,1,1.210000,0,0,0,0,0,0
49680,1.0,18,10.0,1,1.000000,0,0,0,0,0,0
49682,1.0,13,14.0,0,1.960000,0,0,1,0,0,0
49700,1.0,16,27.0,1,7.290000,0,0,1,1,0,0
49703,1.0,18,16.0,0,2.560000,0,0,0,0,0,0
49778,1.0,12,38.0,1,14.440000,0,0,1,1,0,0
49804,1.0,13,9.0,0,0.810000,0,0,1,0,0,0
49805,1.0,16,5.0,1,0.250000,0,0,1,1,0,0
49839,1.0,14,50.0,0,25.000000,0,0,1,0,0,0
49896,1.0,11,48.0,0,23.040001,0,0,1,0,0,0
49966,1.0,20,7.0,1,0.490000,0,0,0,0,1,1
50212,1.0,13,26.0,0,6.760000,0,0,0,0,0,0
50231,1.0,13,8.0,1,0.640000,0,0,0,0,0,0
50247,1.0,16,10.0,0,1.000000,0,0,1,0,0,0
50248,1.0,16,10.0,1,1.000000,0,0,1,1,0,0
50258,1.0,12,38.0,0,14.440000,0,0,1,0,0,0
50369,1.0,18,20.0,0,4.000000,0,0,1,0,0,0
50421,1.0,16,5.0,0,0.250000,0,0,1,0,0,0
50475,1.0,12,9.0,1,0.810000,0,0,0,0,0,0
50559,1.0,12,13.0,0,1.690000,0,0,1,0,0,0
50631,1.0,18,39.0,0,15.210000,0,0,0,0,1,0
50663,1.0,12,10.0,0,1.000000,0,0,1,0,0,0

In [69]:
#part b-c

#b7=0, b8=0, b9=0, and b10=0
#there are 4 restrictions
model = sm.GLS(y,X).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            GLS Regression Results
==============================================================================
Dep. Variable:                  lwage   R-squared:                       0.962
Model:                            GLS   Adj. R-squared:                  0.962
Method:                 Least Squares   F-statistic:                 1.309e+04
Date:                Tue, 20 Mar 2018   Prob (F-statistic):               0.00
Time:                        23:41:00   Log-Likelihood:                -4264.8
No. Observations:                5135   AIC:                             8550.
Df Residuals:                    5125   BIC:                             8615.
Df Model:                          10
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
educ               0.1626      0.002     86.125      0.000       0.159       0.166
exp                0.0369      0.002     16.291      0.000       0.032       0.041
female             0.0093      0.027      0.345      0.730      -0.044       0.062
exp_sq            -0.0525      0.005    -11.249      0.000      -0.062      -0.043
union              0.1459      0.077      1.888      0.059      -0.006       0.297
female*union      -0.1881      0.111     -1.690      0.091      -0.406       0.030
married            0.2081      0.027      7.684      0.000       0.155       0.261
married*female    -0.2038      0.035     -5.804      0.000      -0.273      -0.135
former             0.1344      0.037      3.643      0.000       0.062       0.207
former*female     -0.1904      0.045     -4.258      0.000      -0.278      -0.103
==============================================================================
Omnibus:                     2332.953   Durbin-Watson:                   1.825
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            50462.556
Skew:                          -1.661   Prob(JB):                         0.00
Kurtosis:                      17.994   Cond. No.                         480.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [71]:
R = [[0,0,0,0,0,0,1,0,0,0],[0,0,0,0,0,0,0,1,0,0],[0,0,0,0,0,0,0,0,1,0],[0,0,0,0,0,0,0,0,0,1]]
wtest = model.wald_test(R)
wtest.summary()

'<F test: F=array([[ 16.82039289]]), p=1.04508123402e-13, df_denom=5125, df_num=4>'